In [2]:
import tensorflow as tf

In [3]:
a=tf.constant(7)
a

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
a.ndim

0

In [5]:
b=tf.constant([4,7])
b

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 7])>

In [6]:
b.ndim

1

In [7]:
b[0].assign(7) #const tensor cannot change
b

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [8]:
changeable_tensor=tf.Variable([7, 89])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 89])>

In [9]:
changeable_tensor[1].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 9])>

In [10]:
# any_tensor[0]=3 is wrong way

In [11]:
# creating two random tensor but same
rand_tensor1=tf.random.Generator.from_seed(7)
rand_tensor1=rand_tensor1.normal(shape=(3,2))
rand_tensor2=tf.random.Generator.from_seed(7)
rand_tensor2=rand_tensor2.normal(shape=(3,2))

rand_tensor1,rand_tensor2,rand_tensor1==rand_tensor2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.2878567 ],
        [-0.8757901 , -0.08857017],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.2878567 ],
        [-0.8757901 , -0.08857017],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [12]:
# shuffling the tensor
not_shuffled=tf.constant([[1,2],
                         [3,4],
                         [5,6]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [13]:
not_shuffled.ndim

2

In [14]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6],
       [3, 4]])>

In [15]:
tf.random.set_seed(7)
tf.random.shuffle(not_shuffled,seed=7)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2],
       [5, 6]])>

In [16]:
tf.ones([10,9])

<tf.Tensor: shape=(10, 9), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [17]:
tf.zeros(shape=(7,6))

<tf.Tensor: shape=(7, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [18]:
# tenosr run faster on gpu than np.array
import numpy as np

In [19]:
np_a=np.arange(1,25,dtype=np.int32)
np_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [20]:
A=tf.constant(np_a,shape=(2,3,4))
B=tf.constant(np_a)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

In [21]:
rank4_tensor=tf.zeros([2,3,4,5])
rank4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [22]:
rank4_tensor.shape,rank4_tensor.ndim,tf.size(rank4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [23]:
# getting first 2 of each element
rank4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [24]:
rank4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
rank2_tensor=tf.constant([[10,7],
                         [3,4]])
rank2_tensor.shape,rank2_tensor.ndim

(TensorShape([2, 2]), 2)

In [26]:
# geting last element of each row
rank2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [27]:
# Add extra dimension to 2 rank tensor
rank3_tensor= rank2_tensor[...,tf.newaxis]
rank3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [28]:
# Alternative to tf.newaxis
tf.expand_dims(rank2_tensor,axis=-1) # -1 means expand last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [29]:
tf.expand_dims(rank2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]])>

In [30]:
tensor=rank2_tensor
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [31]:
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [32]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

# tensor*10 is slow than tf.multipy(tensor,10)

In [33]:
tf.matmul(tensor,tensor) # dot product

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [34]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [35]:
test=tf.constant([[1],
                  [2],
                  [3]])
test2=tf.constant([[1,2,3]])
test.shape,test2.shape,test@test2

(TensorShape([3, 1]),
 TensorShape([1, 3]),
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])>)

In [36]:
e=tf.cast(test2,dtype=tf.dtypes.float32)
e

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 2., 3.]], dtype=float32)>

In [37]:
tf.transpose(e)

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[1.],
       [2.],
       [3.]], dtype=float32)>

In [38]:
# Aggregation method
# min
# max
# mean
# median

In [39]:
E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([71, 75, 87,  0, 90, 15, 47, 37, 41, 58, 14, 61, 81, 69, 17, 33, 50,
       95, 97, 78, 81, 55, 38,  3, 66, 48,  5, 39, 94, 10,  4, 98,  1, 21,
       46, 79, 52, 61, 60, 71, 80, 62, 68, 74, 14, 28, 53, 58, 71, 30])>

In [40]:
E.shape,E.ndim,tf.size(E)

(TensorShape([50]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [41]:
tf.reduce_min(E),np.min(E)

(<tf.Tensor: shape=(), dtype=int32, numpy=0>, 0)

In [42]:
tf.reduce_max(E),np.max(E)

(<tf.Tensor: shape=(), dtype=int32, numpy=98>, 98)

In [43]:
tf.reduce_mean(E),np.mean(E)

(<tf.Tensor: shape=(), dtype=int32, numpy=51>, 51.72)

In [44]:
tf.reduce_sum(E),np.sum(E)

(<tf.Tensor: shape=(), dtype=int32, numpy=2586>, 2586)

In [45]:
E=tf.cast(E,dtype=tf.dtypes.float32)
tf.math.reduce_variance(E),np.var(E)

(<tf.Tensor: shape=(), dtype=float32, numpy=803.4816>, 803.48157)

In [46]:
tf.math.reduce_std(E),np.std(E)

(<tf.Tensor: shape=(), dtype=float32, numpy=28.34575>, 28.34575)

In [47]:
# sqeezing the tensor
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [48]:
g_squeeze=tf.squeeze(G)
g_squeeze

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [54]:
# one hot encoding from tensorflow
some_list=[1,2,3,4]
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [55]:
tf.one_hot(some_list,depth=4,on_value='i love deep learning',off_value='i also like dance')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'i also like dance', b'i love deep learning',
        b'i also like dance', b'i also like dance'],
       [b'i also like dance', b'i also like dance',
        b'i love deep learning', b'i also like dance'],
       [b'i also like dance', b'i also like dance', b'i also like dance',
        b'i love deep learning'],
       [b'i also like dance', b'i also like dance', b'i also like dance',
        b'i also like dance']], dtype=object)>

In [56]:
tf.square(some_list)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  4,  9, 16])>

In [59]:
tf.sqrt(tf.cast(some_list,dtype=tf.float32))

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.       , 1.4142135, 1.7320508, 2.       ], dtype=float32)>

In [61]:
tf.math.log(tf.cast(some_list,dtype=tf.float32))

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.       , 0.6931472, 1.0986123, 1.3862944], dtype=float32)>

In [64]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [65]:
!nvidia-smi

Sun Jun 30 13:31:46 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.99                 Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   40C    P8              2W /   30W |    2301MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----